package it.dtsoft.tennismatchtracker.dataaccess.dao;


import java.io.Serializable;
import java.sql.Timestamp;

 /**
  * Match Value Object.
  * This class is value object representing database table tmt_match
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Match implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int matchId;
    private int firstPlayerId;
    private int secondPlayerId;
    private Timestamp startTime;
    private Timestamp endTime;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Match () {

    }

    public Match (int matchIdIn) {

          this.matchId = matchIdIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getMatchId() {
          return this.matchId;
    }
    public void setMatchId(int matchIdIn) {
          this.matchId = matchIdIn;
    }

    public int getFirstPlayerId() {
          return this.firstPlayerId;
    }
    public void setFirstPlayerId(int firstPlayerIdIn) {
          this.firstPlayerId = firstPlayerIdIn;
    }

    public int getSecondPlayerId() {
          return this.secondPlayerId;
    }
    public void setSecondPlayerId(int secondPlayerIdIn) {
          this.secondPlayerId = secondPlayerIdIn;
    }

    public Timestamp getStartTime() {
          return this.startTime;
    }
    public void setStartTime(Timestamp startTimeIn) {
          this.startTime = startTimeIn;
    }

    public Timestamp getEndTime() {
          return this.endTime;
    }
    public void setEndTime(Timestamp endTimeIn) {
          this.endTime = endTimeIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int matchIdIn,
          int firstPlayerIdIn,
          int secondPlayerIdIn,
          Timestamp startTimeIn,
          Timestamp endTimeIn) {
          this.matchId = matchIdIn;
          this.firstPlayerId = firstPlayerIdIn;
          this.secondPlayerId = secondPlayerIdIn;
          this.startTime = startTimeIn;
          this.endTime = endTimeIn;
    }


    /** 
     * hasEqualMapping-method will compare two Match instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Match valueObject) {

          if (valueObject.getMatchId() != this.matchId) {
                    return(false);
          }
          if (valueObject.getFirstPlayerId() != this.firstPlayerId) {
                    return(false);
          }
          if (valueObject.getSecondPlayerId() != this.secondPlayerId) {
                    return(false);
          }
          if (this.startTime == null) {
                    if (valueObject.getStartTime() != null)
                           return(false);
          } else if (!this.startTime.equals(valueObject.getStartTime())) {
                    return(false);
          }
          if (this.endTime == null) {
                    if (valueObject.getEndTime() != null)
                           return(false);
          } else if (!this.endTime.equals(valueObject.getEndTime())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Match, mapping to table tmt_match\n");
        out.append("Persistent attributes: \n"); 
        out.append("matchId = " + this.matchId + "\n"); 
        out.append("firstPlayerId = " + this.firstPlayerId + "\n"); 
        out.append("secondPlayerId = " + this.secondPlayerId + "\n"); 
        out.append("startTime = " + this.startTime + "\n"); 
        out.append("endTime = " + this.endTime + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Match cloned = new Match();

        cloned.setMatchId(this.matchId); 
        cloned.setFirstPlayerId(this.firstPlayerId); 
        cloned.setSecondPlayerId(this.secondPlayerId); 
        if (this.startTime != null)
             cloned.setStartTime((Timestamp)this.startTime.clone()); 
        if (this.endTime != null)
             cloned.setEndTime((Timestamp)this.endTime.clone()); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}